const COMPOSITE_CEP = {
  id: 'cep',
  name: 'CEP (Cidade, Estado ou País)',
  icon: 'fa-map-location-dot',
};

const CATEGORIES = [
  { id: 1,   name: 'Nome (pessoa)',                    icon: 'fa-user' },
  { id: 2,   name: 'Animal',                           icon: 'fa-paw' },
  { id: 3,   name: 'Cidade',                           icon: 'fa-city' },
  { id: 4,   name: 'Estado',                           icon: 'fa-map' },
  { id: 5,   name: 'País',                             icon: 'fa-globe' },
  { id: 6,   name: 'Cor',                              icon: 'fa-palette' },
  { id: 7,   name: 'Objeto',                           icon: 'fa-cube' },
  { id: 8,   name: 'Comida / Prato',                   icon: 'fa-utensils' },
  { id: 9,   name: 'Marca',                            icon: 'fa-tag' },
  { id: 10,  name: 'Filme',                            icon: 'fa-film' },
  { id: 11,  name: 'Série de TV',                      icon: 'fa-tv' },
  { id: 12,  name: 'Livro',                            icon: 'fa-book' },
  { id: 13,  name: 'Música',                           icon: 'fa-music' },
  { id: 14,  name: 'Banda ou Cantor(a)',               icon: 'fa-guitar' },
  { id: 15,  name: 'Ator ou Atriz',                    icon: 'fa-star' },
  { id: 16,  name: 'Personagem Fictício',              icon: 'fa-masks-theater' },
  { id: 17,  name: 'Esporte',                          icon: 'fa-futbol' },
  { id: 18,  name: 'Atleta',                           icon: 'fa-person-running' },
  { id: 19,  name: 'Time ou Clube',                    icon: 'fa-shield-halved' },
  { id: 20,  name: 'Planta',                           icon: 'fa-seedling' },
  { id: 21,  name: 'Flor',                             icon: 'fa-fan' },
  { id: 22,  name: 'Fruta',                            icon: 'fa-apple-whole' },
  { id: 23,  name: 'Legume ou Verdura',                icon: 'fa-carrot' },
  { id: 24,  name: 'Instrumento Musical',              icon: 'fa-drum' },
  { id: 25,  name: 'Profissão',                        icon: 'fa-briefcase' },
  { id: 26,  name: 'Meio de Transporte',               icon: 'fa-car' },
  { id: 27,  name: 'Bebida',                           icon: 'fa-martini-glass' },
  { id: 28,  name: 'Roupa ou Vestuário',               icon: 'fa-shirt' },
  { id: 29,  name: 'Parte do Corpo',                   icon: 'fa-hand' },
  { id: 30,  name: 'Doença',                           icon: 'fa-virus' },
  { id: 31,  name: 'Elemento Químico',                 icon: 'fa-flask' },
  { id: 32,  name: 'Planeta ou Astro',                 icon: 'fa-moon' },
  { id: 33,  name: 'Rio',                              icon: 'fa-water' },
  { id: 34,  name: 'Montanha ou Serra',                icon: 'fa-mountain' },
  { id: 35,  name: 'Capital de País',                  icon: 'fa-landmark' },
  { id: 36,  name: 'Moeda',                            icon: 'fa-coins' },
  { id: 37,  name: 'Idioma',                           icon: 'fa-language' },
  { id: 38,  name: 'Religião',                         icon: 'fa-place-of-worship' },
  { id: 39,  name: 'Personagem Histórico',             icon: 'fa-scroll' },
  { id: 40,  name: 'Super-herói',                      icon: 'fa-bolt' },
  { id: 41,  name: 'Vilão',                            icon: 'fa-skull' },
  { id: 42,  name: 'Personagem de Desenho',            icon: 'fa-wand-magic-sparkles' },
  { id: 43,  name: 'Brinquedo',                        icon: 'fa-gamepad' },
  { id: 44,  name: 'Jogo de Tabuleiro',                icon: 'fa-chess' },
  { id: 45,  name: 'Aplicativo / App',                 icon: 'fa-mobile-screen' },
  { id: 46,  name: 'Empresa de Tecnologia',            icon: 'fa-laptop-code' },
  { id: 47,  name: 'Rede Social',                      icon: 'fa-hashtag' },
  { id: 48,  name: 'Celebridade',                      icon: 'fa-camera' },
  { id: 49,  name: 'Político',                         icon: 'fa-gavel' },
  { id: 50,  name: 'Adjetivo',                         icon: 'fa-spell-check' },
  { id: 51,  name: 'Verbo',                            icon: 'fa-pen' },
  { id: 52,  name: 'Doce ou Sobremesa',                icon: 'fa-candy-cane' },
  { id: 53,  name: 'Restaurante ou Lanchonete',        icon: 'fa-burger' },
  { id: 54,  name: 'Dança',                            icon: 'fa-music' },
  { id: 55,  name: 'Gênero Musical',                   icon: 'fa-headphones' },
  { id: 56,  name: 'Gênero de Filme',                  icon: 'fa-clapperboard' },
  { id: 57,  name: 'Mineral ou Pedra Preciosa',        icon: 'fa-gem' },
  { id: 58,  name: 'Constelação',                      icon: 'fa-star-of-david' },
  { id: 59,  name: 'Personagem da Marvel',             icon: 'fa-spider' },
  { id: 60,  name: 'Personagem da DC',                 icon: 'fa-mask' },
  { id: 61,  name: 'Personagem de Harry Potter',       icon: 'fa-hat-wizard' },
  { id: 62,  name: 'Personagem de Star Wars',          icon: 'fa-jedi' },
  { id: 63,  name: 'Ferramenta',                       icon: 'fa-wrench' },
  { id: 64,  name: 'Eletrodoméstico',                  icon: 'fa-blender' },
  { id: 65,  name: 'Móvel (de casa)',                  icon: 'fa-couch' },
  { id: 66,  name: 'Material Escolar',                 icon: 'fa-pencil' },
  { id: 67,  name: 'País da África',                   icon: 'fa-globe-africa' },
  { id: 68,  name: 'País da Europa',                   icon: 'fa-globe-europe' },
  { id: 69,  name: 'País da Ásia',                     icon: 'fa-globe-asia' },
  { id: 70,  name: 'País da América',                  icon: 'fa-globe-americas' },
  { id: 71,  name: 'Cidade do Brasil',                 icon: 'fa-building' },
  { id: 72,  name: 'Bioma',                            icon: 'fa-tree' },
  { id: 73,  name: 'Palavra em Inglês',                icon: 'fa-flag' },
  { id: 74,  name: 'Jogo de Videogame',                icon: 'fa-gamepad' },
  { id: 75,  name: 'Personagem de Videogame',          icon: 'fa-ghost' },
  { id: 76,  name: 'Animal Marinho',                   icon: 'fa-fish' },
  { id: 77,  name: 'Inseto',                           icon: 'fa-bug' },
  { id: 78,  name: 'Ave',                              icon: 'fa-dove' },
  { id: 79,  name: 'Mamífero',                         icon: 'fa-horse' },
  { id: 80,  name: 'Réptil',                           icon: 'fa-dragon' },
  { id: 81,  name: 'Animal da Fazenda',                icon: 'fa-cow' },
  { id: 82,  name: 'Animal da Selva',                  icon: 'fa-hippo' },
  { id: 83,  name: 'Signo do Zodíaco',                 icon: 'fa-yin-yang' },
  { id: 84,  name: 'Deus da Mitologia',                icon: 'fa-sun' },
  { id: 85,  name: 'Animal Mítico ou Fictício',        icon: 'fa-dragon' },
  { id: 86,  name: 'Aparelho Eletrônico',              icon: 'fa-microchip' },
  { id: 87,  name: 'Personagem de Anime',              icon: 'fa-face-smile' },
  { id: 88,  name: 'Mangá ou Anime',                   icon: 'fa-book-open' },
  { id: 89,  name: 'País da Oceania',                  icon: 'fa-globe' },
  { id: 90,  name: 'Invenção ou Descoberta',           icon: 'fa-lightbulb' },
  { id: 91,  name: 'Cientista ou Naturalista',         icon: 'fa-microscope' },
  { id: 92,  name: 'Ditado ou Expressão Popular',      icon: 'fa-comment-dots' },
  { id: 93,  name: 'Mar ou Oceano',                    icon: 'fa-water' },
  { id: 94,  name: 'Ilha',                             icon: 'fa-umbrella-beach' },
  { id: 95,  name: 'Acessório de Moda',                icon: 'fa-glasses' },
  { id: 96,  name: 'Material de Construção',           icon: 'fa-helmet-safety' },
  { id: 97,  name: 'Youtuber ou Influencer',           icon: 'fa-video' },
  { id: 98,  name: 'Programa de Auditório',            icon: 'fa-microphone' },
  { id: 99,  name: 'Banda de Rock',                    icon: 'fa-record-vinyl' },
  { id: 100, name: 'Comida Típica Brasileira',         icon: 'fa-pepper-hot' },
  // Creative & funny categories
  { id: 101, name: 'Chamaria para um Churrasco',       icon: 'fa-fire' },
  { id: 102, name: 'Coisa de Mãe',                     icon: 'fa-heart' },
  { id: 103, name: 'Representa o Brasil',              icon: 'fa-flag' },
  { id: 104, name: 'Perrengue Chique',                 icon: 'fa-face-grimace' },
  { id: 105, name: 'Deveria ser Crime',                icon: 'fa-gavel' },
  { id: 106, name: 'Pior Presente de Aniversário',     icon: 'fa-gift' },
  { id: 107, name: 'Coisa Estranha que Tenho em Casa', icon: 'fa-house' },
  { id: 108, name: 'Tem na Geladeira',                 icon: 'fa-temperature-low' },
  { id: 109, name: 'Tem na Bolsa',                     icon: 'fa-bag-shopping' },
  { id: 110, name: 'Tem no Banheiro',                  icon: 'fa-bath' },
  { id: 111, name: 'No Meu Casamento vai Ter',         icon: 'fa-ring' },
  { id: 112, name: 'Animal Fantástico',                icon: 'fa-dragon' },
  { id: 113, name: 'Lugar Assombrado',                 icon: 'fa-ghost' },
  { id: 114, name: 'O que NÃO Fazer num 1º Encontro',  icon: 'fa-heart-crack' },
  { id: 115, name: 'O que me Irrita',                  icon: 'fa-face-angry' },
  { id: 116, name: 'Antes de Morrer Quero…',           icon: 'fa-bucket' },
  { id: 117, name: 'Não me Orgulho de…',               icon: 'fa-face-flushed' },
  { id: 118, name: 'Invenção Maluca para Facilitar a Vida', icon: 'fa-lightbulb' },
  { id: 119, name: 'O que Fazer ao Encontrar um Alienígena', icon: 'fa-user-astronaut' },
  { id: 120, name: 'Medo de…',                         icon: 'fa-skull' },
  { id: 121, name: 'Mania Estranha',                   icon: 'fa-brain' },
  { id: 122, name: 'Música que Acaba com Qualquer Festa', icon: 'fa-ban' },
  { id: 123, name: 'Pior Moda que Já Adotei',          icon: 'fa-shirt' },
  { id: 124, name: 'Motivo para Rir',                  icon: 'fa-face-laugh' },
  { id: 125, name: 'Comida Exótica',                   icon: 'fa-bowl-food' },
  { id: 126, name: 'Hashtag Inventada',                icon: 'fa-hashtag' },
  { id: 127, name: 'Slogan para um Produto Novo',      icon: 'fa-bullhorn' },
  { id: 128, name: 'Nome de um Reality Show',          icon: 'fa-tv' },
  { id: 129, name: 'Minha Banda se Chama…',            icon: 'fa-guitar' },
  { id: 130, name: 'Apelido de Casal',                 icon: 'fa-heart' },
  { id: 131, name: 'Nome de uma Ilha Deserta',         icon: 'fa-umbrella-beach' },
  { id: 132, name: 'Cor de Esmalte (sem cores básicas)', icon: 'fa-paint-roller' },
  { id: 133, name: 'Personagem de Desenho Inexistente', icon: 'fa-pen-nib' },
  { id: 134, name: 'Título para uma Novela Mexicana',  icon: 'fa-film' },
  { id: 135, name: 'Nome do Meu Livro',                icon: 'fa-book' },
  { id: 136, name: 'Causa de Morte Inusitada',         icon: 'fa-skull-crossbones' },
  { id: 137, name: 'Crime',                            icon: 'fa-handcuffs' },
  { id: 138, name: 'Motivo de Divórcio',               icon: 'fa-ring' },
  { id: 139, name: 'Superpoder',                       icon: 'fa-bolt' },
  { id: 140, name: 'Desastre Natural',                 icon: 'fa-tornado' },
  { id: 141, name: 'Cobertura de Pizza',               icon: 'fa-pizza-slice' },
  { id: 142, name: 'Minha Sogra é… (MSE)',             icon: 'fa-face-rolling-eyes' },
  { id: 143, name: 'App ou Site',                      icon: 'fa-mobile-screen' },
];

const PRESETS = [
  {
    id: 'padrao',
    name: 'Padrão',
    description: 'O clássico! Nome, Animal, CEP, Cor...',
    icon: 'fa-star',
    color: '#6C63FF',
    categories: ['cep', 1, 2, 6, 7, 8, 9, 10],
  },
  {
    id: 'familia',
    name: 'Família',
    description: 'Para jogar com as crianças',
    icon: 'fa-house-user',
    color: '#FF6584',
    categories: [1, 2, 22, 6, 43, 52, 42, 28],
  },
  {
    id: 'natureza',
    name: 'Natureza',
    description: 'Fauna, flora e o planeta',
    icon: 'fa-leaf',
    color: '#43D9AD',
    categories: [2, 20, 21, 22, 72, 33, 34, 57],
  },
  {
    id: 'cultura_pop',
    name: 'Cultura Pop',
    description: 'Filmes, séries, músicas e mais',
    icon: 'fa-fire',
    color: '#FF9F43',
    categories: [10, 11, 14, 16, 40, 87, 74, 47],
  },
  {
    id: 'esportes',
    name: 'Esportes',
    description: 'Para os fãs de esporte',
    icon: 'fa-trophy',
    color: '#54A0FF',
    categories: [17, 18, 19, 5, 3, 9, 13, 26],
  },
  {
    id: 'geografia',
    name: 'Geografia',
    description: 'Países, rios, montanhas e mais',
    icon: 'fa-globe',
    color: '#5F27CD',
    categories: [5, 35, 3, 33, 34, 93, 94, 71],
  },
  {
    id: 'ciencias',
    name: 'Mundo Científico',
    description: 'Para os amantes da ciência',
    icon: 'fa-flask',
    color: '#00D2D3',
    categories: [31, 32, 91, 90, 2, 20, 30, 57],
  },
  {
    id: 'extremo',
    name: 'Modo Extremo',
    description: 'Só para os corajosos!',
    icon: 'fa-skull-crossbones',
    color: '#EE5A24',
    categories: [59, 61, 62, 55, 84, 85, 83, 58, 37, 92],
  },
  {
    id: 'diferentes',
    name: 'Diferentes',
    description: 'Categorias criativas e inesperadas',
    icon: 'fa-shuffle',
    color: '#A29BFE',
    categories: [126, 127, 128, 129, 130, 132, 134, 141],
  },
  {
    id: 'engracados',
    name: 'Engraçados',
    description: 'Vai dar risada, pode apostar!',
    icon: 'fa-face-laugh-squint',
    color: '#FDCB6E',
    categories: [104, 105, 106, 114, 115, 120, 121, 122, 123, 142],
  },
  {
    id: 'brasileiro',
    name: 'Brasileiro',
    description: 'Jeitinho brasileiro raiz',
    icon: 'fa-flag',
    color: '#00B894',
    categories: [103, 101, 102, 100, 108, 71, 72, 8],
  },
  {
    id: 'reflexivo',
    name: 'Reflexivo',
    description: 'Revela a sua personalidade',
    icon: 'fa-brain',
    color: '#E17055',
    categories: [116, 117, 118, 119, 121, 124, 133, 135],
  },
  {
    id: 'teen',
    name: 'Teen',
    description: 'O favorito dos jovens',
    icon: 'fa-mobile-screen',
    color: '#fd79a8',
    categories: [47, 97, 143, 126, 128, 75, 87, 14, 48, 130],
  },
];

function getCategoryById(id) {
  if (id === 'cep') return COMPOSITE_CEP;
  return CATEGORIES.find(c => c.id === id) || null;
}

function getCategoriesByIds(ids) {
  return ids.map(getCategoryById).filter(Boolean);
}

function getPresetById(id) {
  return PRESETS.find(p => p.id === id) || null;
}
